version: "3.8"
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: sleep infinity
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - POSITION_DATABASE=position_database
      - POSITION_DATABASE_HOST=database
      - POSITION_DATABASE_PASSWORD=postgres
      - POSITION_DATABASE_USER=postgres
      - VERSION=${VERSION}
    ports:
      - "8080:8080"
    volumes:
      - ../:/app/
  database:
    build: database/
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=position_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 30s
      retries: 5
    volumes:
      - data_volume:/var/lib/postgresql/data
  pgadmin:
    build: pgadmin/
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "9000:80"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
volumes:
  data_volume:
  pgadmin_volume:
